"""
LLM Provider Interface Contract.

Defines the normalized abstraction for all LLM provider adapters. Every agent
invocation that requires AI model execution passes through this interface. No
agent communicates directly with any LLM provider SDK.

Authority:
    BACKEND_MODULE_ARCHITECTURE.md Section 4.6 (interfaces module responsibilities)
    BACKEND_MODULE_ARCHITECTURE.md Section 7.2 (LLMProvider contract)
    SYSTEM_ARCHITECTURE.md Section 4.8 (LLM Gateway)

Implementors:
    src/backend/infrastructure/llm_gateway/anthropic_adapter.py
    (future: OpenAIAdapter, AzureOpenAIAdapter, GeminiAdapter)

Consumers:
    src/backend/infrastructure/llm_gateway/ (gateway routes to adapter via this interface)
    src/backend/agents/base/ (agents invoke through this interface only)
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any


# ---------------------------------------------------------------------------
# Request / Response models (interface-local DTOs)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class LLMRequest:
    """
    Normalized LLM invocation request.

    All fields are provider-agnostic. The implementing adapter translates
    this request into the provider-specific format before transmission.

    Attributes:
        model_id: The model identifier used by the LLM adapter factory to
            route to the correct provider adapter (e.g., "claude-sonnet-4-6").
        system_prompt: The system-level instruction prompt. Sanitized by the
            LLM Gateway before transmission.
        user_prompt: The user-facing content prompt. Sanitized by the
            LLM Gateway before transmission.
        max_tokens: Maximum number of tokens to generate. Enforced by the
            adapter at the provider level.
        temperature: Sampling temperature (0.0–1.0). 0.0 for deterministic,
            higher for creative outputs.
        stop_sequences: Optional list of sequences at which to stop generation.
        agent_id: The agent identifier that originated this request. Used for
            observability attribution.
        correlation_id: Request correlation ID for distributed tracing.
        extra_params: Provider-specific parameters not covered by this contract.
            Use sparingly — prefer standardized fields for portability.
    """

    model_id: str
    system_prompt: str
    user_prompt: str
    max_tokens: int
    temperature: float = 0.0
    stop_sequences: list[str] = field(default_factory=list)
    agent_id: str = ""
    correlation_id: str = ""
    extra_params: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class LLMResponse:
    """
    Normalized LLM response.

    All provider-specific response formats are normalized to this model by
    the adapter before being returned. Consuming code never sees raw provider
    responses.

    Attributes:
        generated_text: The text generated by the LLM. Already decoded to
            a Python string.
        finish_reason: The reason generation stopped. Standard values:
            "stop" (stop sequence or end of response), "length" (max_tokens
            reached), "error" (provider error during generation).
        input_tokens: Number of tokens consumed from the prompt.
        output_tokens: Number of tokens in the generated response.
        model_id: The model identifier that served this response. May differ
            from the requested model_id if the provider performed routing.
        provider: The provider name that handled this request (e.g.,
            "anthropic", "openai").
        latency_ms: Time from request dispatch to response receipt, in
            milliseconds.
        raw_response: The raw provider response for debugging. Not used
            in application logic. Stripped before logging.
    """

    generated_text: str
    finish_reason: str
    input_tokens: int
    output_tokens: int
    model_id: str
    provider: str
    latency_ms: float
    raw_response: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Interface contract
# ---------------------------------------------------------------------------


class LLMInterface(ABC):
    """
    Abstract contract for all LLM provider adapters.

    Every LLM provider implementation must satisfy this contract exactly.
    The LLM Gateway routes requests to the correct implementing adapter;
    agents and services only interact with this abstract type.

    Contract invariants:
        - Every call to invoke() must produce a normalized LLMResponse.
        - The adapter must never expose provider-specific types to the caller.
        - The adapter must record invocation metrics before returning.
        - Token budget enforcement must be applied before transmission.
        - All responses must include accurate token usage statistics.

    Raises:
        LLMProviderError: On any provider-side failure (4xx, 5xx, timeout).
        LLMTokenBudgetExceededError: When the request exceeds configured limits.
        LLMRateLimitError: When the provider rate limit is reached.
    """

    @abstractmethod
    async def invoke(self, request: LLMRequest) -> LLMResponse:
        """
        Invoke the LLM provider with the normalized request.

        Implementations must:
            1. Validate the request against this model's constraints.
            2. Translate the LLMRequest to the provider-specific format.
            3. Transmit the request to the provider endpoint.
            4. Receive the provider-specific response.
            5. Normalize the provider-specific response to LLMResponse.
            6. Return the normalized response to the caller.

        Args:
            request: The normalized LLM invocation request.

        Returns:
            LLMResponse: The normalized response from the provider.

        Raises:
            LLMProviderError: If the provider returns an error response.
            LLMRateLimitError: If the provider rate limit is exhausted.
            LLMTokenBudgetExceededError: If the request exceeds token limits.
        """

    @abstractmethod
    async def check_availability(self) -> bool:
        """
        Check whether the LLM provider is currently reachable.

        Used by the health check endpoint and the LLM Gateway's circuit
        breaker logic. Must not raise on connectivity failure — must return
        False instead.

        Returns:
            bool: True if the provider is reachable, False otherwise.
        """

    @abstractmethod
    def get_model_id(self) -> str:
        """
        Return the canonical model identifier this adapter serves.

        Used by the LLM adapter factory to register this adapter against
        its model ID in the routing table.

        Returns:
            str: The model identifier (e.g., "claude-sonnet-4-6").
        """

    @abstractmethod
    def get_provider_name(self) -> str:
        """
        Return the canonical provider name for this adapter.

        Used for observability attribution and audit records.

        Returns:
            str: The provider name (e.g., "anthropic", "openai").
        """

    @abstractmethod
    def get_max_context_tokens(self) -> int:
        """
        Return the maximum context window size in tokens for this model.

        Used by the LLM Gateway and agents to enforce token budget limits
        before constructing prompts.

        Returns:
            int: Maximum context tokens supported by this model.
        """
