"""Mermaid generator: converts DiagramDefinition to Mermaid source text."""

from __future__ import annotations

from typing import List
from .models import DiagramDefinition


def build_mermaid(defn: DiagramDefinition) -> str:
    """Produce a Mermaid source string from a DiagramDefinition.

    This implementation is deterministic and avoids external calls.
    """
    lines: List[str] = ["%% Mermaid generated by mermaid_generator","graph TD"]
    # nodes
    for n in defn.nodes:
        label = n.label.replace("\n", " ")
        lines.append(f'"{n.node_id}"["{label}"]')
    # edges
    for e in defn.edges:
        lbl = f'|"{e.label}"|' if e.label else ""
        lines.append(f'"{e.source}" -->{lbl} "{e.target}"')
    return "\n".join(lines)


class MermaidGenerator:
    """Generate Mermaid source for diagram definitions."""

    def generate(self, definition: DiagramDefinition) -> str:
        return build_mermaid(definition)


__all__ = ["MermaidGenerator", "build_mermaid"]
